import { defineConfig } from "vitest/config";

export default defineConfig({
  esbuild: { jsx: "automatic" },
  test: {
    environment: "node",
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "json"],
      include: [
        "src/lib/**/*.ts",
        "src/app/api/**/*.ts",
        "src/components/dashboard/navigation.ts",
        "src/components/dashboard/SupportChat.tsx",
        "src/app/**/reviews/reviews-client.tsx",
        "src/app/**/rank-tracker/ranking-client.tsx",
        "src/app/**/dashboard/overview-client.tsx",
        "src/app/**/surveys/**/survey-editor.tsx",
        "src/app/**/review-analytics-client.tsx",
        "src/app/**/survey-client.tsx",
        "src/app/**/challenge/challenge-client.tsx",
        "src/app/**/challenge/day-detail.tsx",
        "src/app/**/challenge/next-actions.tsx",
        "src/app/**/challenge/journey.tsx",
        "src/app/**/challenge/action-guide.tsx",
        "src/app/**/roi/google-results-client.tsx",
      ],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.test.tsx",
        "src/lib/prisma.ts",
        "src/app/api/**/route.test.ts",
      ],
      thresholds: {
        "src/lib/aio-comparison.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/google-search-keywords.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/analytics/queries/sync/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/action-guide*.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/challenge/action-guide.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/challenge/guide-draft/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/google-leads.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/google-lead-store.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/google-lead-access.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/google-performance.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/google-results/**/*.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/roi/google-results-client.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/challenge-journey.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/challenge/journey.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/rank-tracker/ranking-client.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/dashboard-rankings.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/rankings/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/challenge-next-actions.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/challenge/next-actions.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/challenge.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/challenge-progress.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/challenge/day-detail.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/challenge-data.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/challenge/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/challenge/challenge-client.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        lines: 95,
        functions: 95,
        branches: 95,
        statements: 95,
        "src/app/**/reviews/reviews-client.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/dashboard/overview-client.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/dashboard-summary.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/overview/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/gbp-direct-reply.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/gbp-review-draft.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/gbp-reviews-sync.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/reviews/sync/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/review-reply-assist.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/gbp/reply/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/reviews/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/google-gbp-oauth.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/survey-builder.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/surveys/**/survey-editor.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/review-analytics-client.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/review-analytics.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/review-analytics-ai.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/survey-respondent.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/**/survey-client.tsx": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/public-survey-answers.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/survey-persistence.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/survey-responses/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/review-generator.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/lib/review-template.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/generate-review/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
        "src/app/api/dashboard/reviews/analytics/route.ts": { lines: 95, functions: 95, branches: 95, statements: 95 },
      },
    },
  },
  resolve: {
    alias: {
      "@": new URL("./src", import.meta.url).pathname,
    },
  },
});
